#!/bin/bash

# Copyright (c) 2024, Rafael Santiago
# All rights reserved.
#
# This source code is licensed under the GPLv2 license found in the
# COPYING.GPLv2 file in the root directory of Eutherpe's source tree.

[[ -z $MPG123_MUST_FAIL ]] && sleep 30m || exit 1