on: push
name: Eutherpe CI
jobs:
  Linux:
    env:
       SKIP_UNSTABLE: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.2' ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-verson }}
    - name: Run Eutherpe unit tests
      shell: bash
      run: |
        cd src
        go test -v internal/*
